#include <stdio.h>
#include <math.h>
#include "control.h"

#define M_PI	3.14159265358979323846
#define HALF_PI	(M_PI/2)

static double sineTable[256];
static int quadrant = 1;		// tracks which quadrant of the wave we are in
static double *sinePointer = sineTable;	// for accessing the sineTable values

/*
 * Populate sineTable with values generated by
 * the function sin(i * HALF_PI / 256)
 */

void generateSineTable(void) {
	int i;
	for(i=0; i < 256; i++) {
		sineTable[i] = sin(i * HALF_PI / 256);

	}
//		printf("%f = %.2f\n", sineTable[i], (sineTable[i]/HALF_PI)*100);
}

/*
 * Called by the timer interrupt handler.
 *
 * Signals the PWM with a percent value based on the current sine value.
 * Increments a pointer through the table of sine values.
 *
 * The 4 case statements refer to the 4 quadrants of the sine wave.
 */

void increment(void)
{
	//int percent = ((*p) / HALF_PI) * 100;
	int percent = (*sinePointer) * 100;

	switch(quadrant)
	{
		case 1:
		{
			signalPWM(percent);

			sinePointer++;

			if(*sinePointer == sineTable[255])
			{
				quadrant++;
			}

		} break;
		case 2:
		{
			signalPWM(percent);

			sinePointer--;

			if(*sinePointer == sineTable[0])
			{
				quadrant++;
			}

		} break;
		case 3:
		{
			signalPWM(-percent);

			sinePointer++;

			if(*sinePointer == sineTable[255])
			{
				quadrant++;
			}

		} break;
		case 4:
		{
			signalPWM(-percent);

			sinePointer--;

			if(*sinePointer == sineTable[0])
			{
				quadrant = 1;
			}

		} break;
	}

}



//	for(int j=0;j<=256;j++) {
//		printf("%20.18lf\n", sineTable[j]);
//	}

/*	for(int i = 0; i < x; i++) {
		for(int j = 0; j < y; j++) {
			if(count > 257)
				break;	
			table[i][j] = sineTable[count];
			count++;
		}
	}
	
	for(int k = 0; k < x; k++) {
		for(int l = 0; l < y; l++) {
			printf("%f  ", table[k][l]);
		}
		printf("\n");
	}
*/
